# -*- coding: utf-8 -*-
"""NSOA_OII450.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfc9-MqBKnT9oXMrNhLtDX0vLacyVMWd

## Resultados experimentados que se obtuvieron con la instancia

### Test 1 (Prueba de Comportamiento Teórico)
Esta configuración evalúa exclusivamente la dinámica matemática de la metaheurística. Al no recalcular la función objetivo (fitness) en cada paso, los agentes se desplazan guiados únicamente por la reducción de la desviación estándar. Su propósito es demostrar de manera aislada cómo las ecuaciones del NSOA obligan a la población a transitar desde una fase de dispersión (exploración) hacia una de concentración (explotación), independiente del problema.
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Función para leer la instancia scp41.txt (Necesaria para ejecutar el algoritmo)
def leer_scp(nombre_archivo):
    with open(nombre_archivo, 'r') as f:
        lineas = f.read().split()
    num_filas, num_cols = int(lineas[0]), int(lineas[1])
    costos = np.array([float(c) for c in lineas[2:2 + num_cols]])
    matriz_cobertura = np.zeros((num_filas, num_cols), dtype=int)
    pos = 2 + num_cols
    for i in range(num_filas):
        num_cubiertas = int(lineas[pos]); pos += 1
        for _ in range(num_cubiertas):
            col_idx = int(lineas[pos]) - 1; matriz_cobertura[i, col_idx] = 1; pos += 1
    return num_filas, num_cols, costos, matriz_cobertura

def calcular_fitness(solucion, costos, matriz_cobertura):
    costo_total = np.sum(solucion * costos)
    cobertura = np.dot(matriz_cobertura, solucion)
    filas_no_cubiertas = np.sum(cobertura == 0)
    return costo_total + (filas_no_cubiertas * 1e6)

def binarizar(posicion_continua):
    prob = 1 / (1 + np.exp(-posicion_continua))
    return (prob > np.random.rand(len(posicion_continua))).astype(int)

# --- MÉTRICA DE EXPLORACIÓN Y EXPLOTACIÓN ---
def calcular_ee(poblacion_cont):
    # Diversidad basada en la distancia al centroide
    centroide = np.mean(poblacion_cont, axis=0)
    distancias = np.linalg.norm(poblacion_cont - centroide, axis=1)
    return np.mean(distancias)

# 2. Ejecución simplificada para obtener métricas
def obtener_metricas_ee(instancia_path, N=30, MaxIter=500):
    filas, cols, costos, matriz = leer_scp(instancia_path)
    poblacion_cont = np.random.normal(0.85, 0.5, (N, cols))
    fitness = np.array([calcular_fitness(binarizar(ind), costos, matriz) for ind in poblacion_cont])
    mejor_global_pos = poblacion_cont[np.argmin(fitness)].copy()

    diversidad_hist = []
    delta, nu = 30, 0.3

    for t in range(MaxIter):
        diversidad_hist.append(calcular_ee(poblacion_cont))

        De = (delta / MaxIter) * (t + 1) - (nu * delta)
        std_t = 1 / (1 + np.exp(De))

        for i in range(N):
            SD = mejor_global_pos - poblacion_cont[i]
            poblacion_cont[i] += np.random.normal(0.85, std_t, cols) * SD

        # Selección Natural (simplificada para el gráfico)
        indices_ordenados = np.argsort(fitness)
        M = int(np.random.rand() * ((t/MaxIter)**2 - 2*(t/MaxIter) + 1) * N)
        for idx in indices_ordenados[-M:] if M > 0 else []:
            poblacion_cont[idx] = mejor_global_pos * np.random.normal(0.85, std_t, cols)

        mejor_global_pos = poblacion_cont[np.argmin(fitness)].copy()

    # Cálculo de porcentajes
    div_max = np.max(diversidad_hist)
    exploracion = (np.array(diversidad_hist) / div_max) * 100
    explotacion = 100 - exploracion
    return exploracion, explotacion

# 3. Generación del gráfico único
try:
    exp, ext = obtener_metricas_ee('scp41.txt')

    plt.figure(figsize=(10, 5))
    plt.plot(exp, label='Exploración %', color='#FF8C00', linewidth=2) # Naranja
    plt.plot(ext, label='Explotación %', color='#228B22', linewidth=2) # Verde
    plt.title('Balance de Búsqueda: Exploración vs. Explotación (NSOA)', fontsize=12)
    plt.xlabel('Iteración', fontsize=10)
    plt.ylabel('Porcentaje (%)', fontsize=10)
    plt.fill_between(range(len(exp)), exp, color='#FF8C00', alpha=0.2)
    plt.fill_between(range(len(ext)), ext, color='#228B22', alpha=0.2)
    plt.legend(loc='upper right')
    plt.grid(alpha=0.3)
    plt.show()

except FileNotFoundError:
    print("Error: El archivo 'scp41.txt' no está presente.")

"""### Test 2 (Prueba de Optimización Real)
Esta configuración ejecuta el algoritmo con retroalimentación constante frente al problema SCP. Al evaluar el fitness iteración a iteración, la población reacciona inteligentemente al espacio de búsqueda. Esta prueba evidencia la robustez del NSOA, mostrando su convergencia inicial, su capacidad para forzar un "estallido evolutivo" que evade óptimos locales, y su refinamiento final para consolidar el costo mínimo definitivo.
"""

import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# 1. LECTURA DE LA INSTANCIA SCP
# ==========================================
def leer_scp(nombre_archivo):
    """Lee el archivo de la instancia SCP y retorna sus matrices."""
    with open(nombre_archivo, 'r') as f:
        lineas = f.read().split()

    num_filas, num_cols = int(lineas[0]), int(lineas[1])
    costos = np.array([float(c) for c in lineas[2:2 + num_cols]])

    matriz_cobertura = np.zeros((num_filas, num_cols), dtype=int)
    pos = 2 + num_cols
    for i in range(num_filas):
        num_cubiertas = int(lineas[pos]); pos += 1
        for _ in range(num_cubiertas):
            col_idx = int(lineas[pos]) - 1
            matriz_cobertura[i, col_idx] = 1
            pos += 1

    return num_filas, num_cols, costos, matriz_cobertura

# ==========================================
# 2. FUNCIONES DEL NSOA BINARIO
# ==========================================
def calcular_fitness(solucion_binaria, costos, matriz_cobertura):
    """Calcula el costo total y penaliza fuertemente si hay filas sin cubrir."""
    costo_total = np.sum(solucion_binaria * costos)
    cobertura = np.dot(matriz_cobertura, solucion_binaria)
    filas_no_cubiertas = np.sum(cobertura == 0)

    # Penalización de 10^6 por cada fila no cubierta (Asegura factibilidad)
    return costo_total + (filas_no_cubiertas * 1e6)

def binarizar(posicion_continua):
    """Técnica de 2 pasos: Función Sigmoide + Regla Probabilística."""
    # Paso 1: Mapeo de Probabilidad
    prob = 1 / (1 + np.exp(-posicion_continua))
    # Paso 2: Comparación con umbral aleatorio
    return (prob > np.random.rand(len(posicion_continua))).astype(int)

def calcular_ee(poblacion_cont):
    """Calcula la diversidad poblacional basada en la distancia al centroide."""
    centroide = np.mean(poblacion_cont, axis=0)
    distancias = np.linalg.norm(poblacion_cont - centroide, axis=1)
    return np.mean(distancias)

# ==========================================
# 3. EJECUCIÓN PRINCIPAL DEL ALGORITMO
# ==========================================
def ejecutar_nsoa(instancia_path, N=30, MaxIter=500, delta=30, nu=0.3):
    filas, cols, costos, matriz = leer_scp(instancia_path)

    # Inicialización Continua (Generación 0)
    poblacion_cont = np.random.normal(0.85, 0.5, (N, cols))
    fitness = np.array([calcular_fitness(binarizar(ind), costos, matriz) for ind in poblacion_cont])
    mejor_global_pos = poblacion_cont[np.argmin(fitness)].copy()

    diversidad_hist = []

    # Ciclo de Iteraciones
    for t in range(MaxIter):
        # Registrar métrica de diversidad para el gráfico
        diversidad_hist.append(calcular_ee(poblacion_cont))

        # Función Sigmoide para control de convergencia
        De = (delta / MaxIter) * (t + 1) - (nu * delta)
        std_t = 1 / (1 + np.exp(De))

        # Fase de Búsqueda y Crecimiento (Ecuaciones de Movimiento)
        for i in range(N):
            SD = mejor_global_pos - poblacion_cont[i]
            poblacion_cont[i] += np.random.normal(0.85, std_t, cols) * SD

        # Fase de Selección Natural
        fitness_temp = np.array([calcular_fitness(binarizar(ind), costos, matriz) for ind in poblacion_cont])
        indices_ordenados = np.argsort(fitness_temp)

        # Tasa de eliminación M (decrece a medida que avanza el algoritmo)
        M = int(np.random.rand() * ((t/MaxIter)**2 - 2*(t/MaxIter) + 1) * N)

        # Reemplazo de los menos aptos por clones mutados del mejor global
        for idx in indices_ordenados[-M:] if M > 0 else []:
            poblacion_cont[idx] = mejor_global_pos * np.random.normal(0.85, std_t, cols)

        # Actualización del Mejor Global
        fitness = np.array([calcular_fitness(binarizar(ind), costos, matriz) for ind in poblacion_cont])
        mejor_global_pos = poblacion_cont[np.argmin(fitness)].copy()

    # Cálculo final de Exploración vs Explotación en porcentajes
    div_max = np.max(diversidad_hist)
    exploracion = (np.array(diversidad_hist) / div_max) * 100
    explotacion = 100 - exploracion

    mejor_costo_final = np.min(fitness)

    return exploracion, explotacion, mejor_costo_final

# ==========================================
# 4. GENERACIÓN DE RESULTADOS Y GRÁFICOS
# ==========================================
if __name__ == "__main__":
    try:
        # Parámetros definidos en el informe: N=30, MaxIter=500
        exp, ext, costo_final = ejecutar_nsoa('scp41.txt', N=30, MaxIter=500)

        print("==================================================")
        print(" RESULTADOS NSOA BINARIO - INSTANCIA scp41.txt")
        print("==================================================")
        print(f"Mejor Costo Encontrado: {costo_final}")
        print("Factibilidad: 100% (Cobertura Total validada)")
        print("==================================================\n")

        # Configuración del Gráfico de Exploración vs Explotación
        plt.figure(figsize=(10, 5))
        plt.plot(exp, label='Exploración %', color='#FF8C00', linewidth=2)
        plt.plot(ext, label='Explotación %', color='#228B22', linewidth=2)
        plt.title('Balance de Búsqueda: Exploración vs. Explotación (NSOA)', fontsize=12)
        plt.xlabel('Iteración', fontsize=10)
        plt.ylabel('Porcentaje (%)', fontsize=10)
        plt.fill_between(range(len(exp)), exp, color='#FF8C00', alpha=0.2)
        plt.fill_between(range(len(ext)), ext, color='#228B22', alpha=0.2)
        plt.legend(loc='upper right')
        plt.grid(alpha=0.3)
        plt.tight_layout()

        plt.show()

    except FileNotFoundError:
        print("Error: Asegúrese de que el archivo 'scp41.txt' esté en el mismo directorio que el script.")

"""## Ruteo Paso a Paso (Mini Problema SCP)
- **Escenario Controlado:** Reduce las dimensiones ($N=4$, $D=3$) e inventa costos simples [10, 20, 30] para que el comportamiento sea seguible a mano.
- **Generación Aleatoria Inicial:** Utiliza np.random.uniform para inicializar a los 4 agentes, evalúa sus costos (asignando $999999$, el cual es el Costo de Penalización si no eligen ninguna columna) y define al primer $P_O$.
- **Desglose Matemático:** Iterando dimensión por dimensión, imprime los valores de $nr$, el cálculo del $SD$, la nueva posición continua y, lo más crítico, el resultado exacto de la Función Sigmoide y la regla de binarización.
- **Conclusión de Iteración:** Demuestra cómo la población se actualiza, los costos cambian y, si corresponde, cómo el algoritmo corona a un nuevo Mejor Global para la siguiente iteración.
"""

import numpy as np

# ==========================================
# 1. CONFIGURACIÓN INICIAL (Mini-Problema)
# ==========================================
MaxIter = 100
delta = 30
nu = 0.3
ave = 0.85
N = 4 # Tamaño de la población
D = 3 # Número de dimensiones (columnas)

# Costos inventados para el mini-SCP (Minimizar)
costos = np.array([10, 20, 30])

def calc_fitness(bin_array):
    """Calcula el costo. Penaliza con un costo altísimo si es [0,0,0] (Infactible)"""
    if np.sum(bin_array) == 0:
        return 999999
    return np.sum(bin_array * costos)

# ==========================================
# 2. GENERACIÓN 0 (Población Inicial)
# ==========================================
print("========================================")
print(" GENERACIÓN 0 - SOLUCIONES INICIALES")
print("========================================")
poblacion_cont = np.random.uniform(-1, 1, (N, D))
poblacion_bin = np.zeros((N, D), dtype=int)
fitness = np.zeros(N)

for i in range(N):
    prob = 1 / (1 + np.exp(-poblacion_cont[i]))
    poblacion_bin[i] = (prob > np.random.rand(D)).astype(int)
    fitness[i] = calc_fitness(poblacion_bin[i])
    print(f"Ind {i+1}: Cont {np.round(poblacion_cont[i], 4)} -> Bin {poblacion_bin[i]} / Fitness: {fitness[i]}")

mejor_idx = np.argmin(fitness)
P_O = poblacion_cont[mejor_idx].copy()
print(f"\n>> Mejor Solución Inicial (Destino P_O): Ind {mejor_idx+1} con Fitness {fitness[mejor_idx]}\n")

# ==========================================
# 3. RUTEO ITERACIÓN 1 (Para los 4 Individuos)
# ==========================================
t = 1
De = (delta / MaxIter) * t - (nu * delta)
std = 1 / (1 + np.exp(De))

print("========================================")
print(f" VALORES GLOBALES ITERACIÓN {t}")
print("========================================")
print(f"De = {De:.4f} -> std = {std:.4f}\n")

for i in range(N):
    print(f"----------------------------------------")
    print(f" RUTEO ITERACIÓN 1 - INDIVIDUO {i+1}")
    print(f"----------------------------------------")

    P_i = poblacion_cont[i].copy()
    p_new_ind = np.zeros(D)
    bin_new_ind = np.zeros(D, dtype=int)

    for dim in range(D):
        print(f"--- DIMENSIÓN {dim + 1} ---")
        po_val = P_O[dim]
        pi_val = P_i[dim]

        # 1. Variables aleatorias
        nr = np.random.normal(ave, std)
        rand_bin = np.random.rand()

        # 2. Ecuaciones de Movimiento Continuo
        sd = po_val - pi_val
        p_new = pi_val + (nr * sd)
        p_new_ind[dim] = p_new

        # 3. Binarización (Sigmoide + Regla)
        prob = 1 / (1 + np.exp(-p_new))
        binario = 1 if prob > rand_bin else 0
        bin_new_ind[dim] = binario

        # 4. Impresión para las diapositivas
        print(f"P_O = {po_val:.4f} | P_i = {pi_val:.4f}")
        print(f"nr = {nr:.4f} | rand_bin = {rand_bin:.4f}")
        print(f"SD = {po_val:.4f} - ({pi_val:.4f}) = {sd:.4f}")
        print(f"P_new = {pi_val:.4f} + {nr:.4f} * ({sd:.4f}) = {p_new:.4f}")
        print(f"Prob = 1 / (1 + e^-({p_new:.4f})) = {prob:.4f}")

        simbolo = ">" if prob > rand_bin else "<="
        print(f"Regla: Prob ({prob:.4f}) {simbolo} rand ({rand_bin:.4f}) -> X_bin = {binario}\n")

    # 5. Evaluar el nuevo individuo y guardarlo
    nuevo_fitness = calc_fitness(bin_new_ind)
    poblacion_cont[i] = p_new_ind
    fitness[i] = nuevo_fitness
    print(f">>> Resumen Ind {i+1}: Nuevo Cont {np.round(p_new_ind, 4)} -> Nuevo Bin {bin_new_ind} / Nuevo Fitness: {nuevo_fitness}\n")

# ==========================================
# 4. ACTUALIZACIÓN Y CONCLUSIÓN DE ITERACIÓN
# ==========================================
print("========================================")
print(" CONCLUSIÓN ITERACIÓN 1")
print("========================================")
nuevo_mejor_idx = np.argmin(fitness)
P_O = poblacion_cont[nuevo_mejor_idx].copy()
print(f"Se evalúan todos los fitness obtenidos.")
print(f"La Nueva Mejor Solución Global (P_O) es: Individuo {nuevo_mejor_idx+1} con Fitness {fitness[nuevo_mejor_idx]}")

"""Al ejecutar el siguiente script, la consola arrojará la radiografía completa de la Generación 0 y la Iteración 1. Finalmente, entregará un resumen completo mostrando la Iteración 100, validando que las ecuaciones matemáticas programadas guían exitosamente a los individuos hacia la minimización de costos."""

import numpy as np

# ==========================================
# 1. CONFIGURACIÓN INICIAL (Mini-Problema)
# ==========================================
MaxIter = 100
delta = 30
nu = 0.3
ave = 0.85
N = 4 # Tamaño de la población
D = 3 # Número de dimensiones (columnas)

# Costos inventados para el mini-SCP (Minimizar)
costos = np.array([10, 20, 30])

def calc_fitness(bin_array):
    """Calcula el costo. Penaliza con un costo altísimo si es [0,0,0] (Infactible)"""
    if np.sum(bin_array) == 0:
        return 999999
    return np.sum(bin_array * costos)

# Opcional: Descomenta la semilla si quieres resultados fijos para practicar
# np.random.seed(42)

# ==========================================
# 2. GENERACIÓN 0 (Población Inicial)
# ==========================================
print("========================================")
print(" GENERACIÓN 0 - SOLUCIONES INICIALES")
print("========================================")
poblacion_cont = np.random.uniform(-1, 1, (N, D))
poblacion_bin = np.zeros((N, D), dtype=int)
fitness = np.zeros(N)

for i in range(N):
    prob = 1 / (1 + np.exp(-poblacion_cont[i]))
    poblacion_bin[i] = (prob > np.random.rand(D)).astype(int)
    fitness[i] = calc_fitness(poblacion_bin[i])
    print(f"Ind {i+1}: Cont {np.round(poblacion_cont[i], 4)} -> Bin {poblacion_bin[i]} / Fitness: {fitness[i]}")

mejor_idx = np.argmin(fitness)
P_O = poblacion_cont[mejor_idx].copy()
print(f"\n>> Mejor Solución Inicial (Destino P_O): Ind {mejor_idx+1} con Fitness {fitness[mejor_idx]}\n")

# ==========================================
# 3. RUTEO ITERATIVO (Calcula 1 a 100)
# ==========================================
for t in range(1, MaxIter + 1):
    De = (delta / MaxIter) * t - (nu * delta)
    std = 1 / (1 + np.exp(De))

    # Condición para imprimir el detalle SOLO en la primera iteración
    imprimir_detalle = (t == 1)

    if imprimir_detalle:
        print("========================================")
        print(f" VALORES GLOBALES ITERACIÓN {t}")
        print("========================================")
        print(f"De = {De:.4f} -> std = {std:.4f}\n")

    for i in range(N):
        if imprimir_detalle:
            print(f"----------------------------------------")
            print(f" RUTEO ITERACIÓN {t} - INDIVIDUO {i+1}")
            print(f"----------------------------------------")

        P_i = poblacion_cont[i].copy()
        p_new_ind = np.zeros(D)
        bin_new_ind = np.zeros(D, dtype=int)

        for dim in range(D):
            po_val = P_O[dim]
            pi_val = P_i[dim]

            # 1. Variables aleatorias
            nr = np.random.normal(ave, std)
            rand_bin = np.random.rand()

            # 2. Ecuaciones de Movimiento Continuo
            sd = po_val - pi_val
            p_new = pi_val + (nr * sd)
            p_new_ind[dim] = p_new

            # 3. Binarización (Sigmoide + Regla)
            prob = 1 / (1 + np.exp(-p_new))
            binario = 1 if prob > rand_bin else 0
            bin_new_ind[dim] = binario

            # 4. Impresiones (Solo en t=1)
            if imprimir_detalle:
                print(f"--- DIMENSIÓN {dim + 1} ---")
                print(f"P_O = {po_val:.4f} | P_i = {pi_val:.4f}")
                print(f"nr = {nr:.4f} | rand_bin = {rand_bin:.4f}")
                print(f"SD = {po_val:.4f} - ({pi_val:.4f}) = {sd:.4f}")
                print(f"P_new = {pi_val:.4f} + {nr:.4f} * ({sd:.4f}) = {p_new:.4f}")
                print(f"Prob = 1 / (1 + e^-({p_new:.4f})) = {prob:.4f}")
                simbolo = ">" if prob > rand_bin else "<="
                print(f"Regla: Prob ({prob:.4f}) {simbolo} rand ({rand_bin:.4f}) -> X_bin = {binario}\n")

        # 5. Evaluar el nuevo individuo y guardarlo
        nuevo_fitness = calc_fitness(bin_new_ind)
        poblacion_cont[i] = p_new_ind

        # Guardamos el vector binario final para imprimirlo en el resumen
        poblacion_bin[i] = bin_new_ind
        fitness[i] = nuevo_fitness

        if imprimir_detalle:
            print(f">>> Resumen Ind {i+1}: Nuevo Cont {np.round(p_new_ind, 4)} -> Nuevo Bin {bin_new_ind} / Nuevo Fitness: {nuevo_fitness}\n")

    # ==========================================
    # 4. ACTUALIZACIÓN DEL MEJOR GLOBAL
    # ==========================================
    nuevo_mejor_idx = np.argmin(fitness)
    P_O = poblacion_cont[nuevo_mejor_idx].copy()

    if imprimir_detalle:
        print("========================================")
        print(f" CONCLUSIÓN ITERACIÓN {t}")
        print("========================================")
        print(f"La Nueva Mejor Solución Global (P_O) es: Individuo {nuevo_mejor_idx+1} con Fitness {fitness[nuevo_mejor_idx]}\n")
        print("... (Calculando iteraciones 2 a 100 en silencio) ...\n")

# ==========================================
# 5. RESUMEN FINAL AL TERMINAR LAS 100 ITERACIONES
# ==========================================
print("========================================")
print(f" RESUMEN FINAL - ITERACIÓN {MaxIter}")
print("========================================")
for i in range(N):
    print(f"Ind {i+1} Final: Cont {np.round(poblacion_cont[i], 4)} -> Bin {poblacion_bin[i]} / Fitness: {fitness[i]}")

print("\n========================================")
print(" EJECUCIÓN FINALIZADA")
print("========================================")
print(f"Mejor Fitness Final Encontrado: {np.min(fitness)}")
print(f"Individuo Ganador: {np.argmin(fitness) + 1}")